services:
  - type: web
    name: spam-detection-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt && pip install -r model/requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
